from dataclasses import dataclass, field
from typing import List, Optional, Dict, Union
import json
from json import JSONDecodeError
from langchain_core.messages import HumanMessage, AIMessage

from LLM.router import routing_query
from LLM.handlers import (
    QuestionGenerator, ResponseFormatter, AnswerScorer, FallbackHandler
)



@dataclass
class QuestionItem:
    index: int
    original_query: str
    generated_question: str
    options: Dict[str, str]   # {"A": "...", "B": "...", "C": "...", "D": "..."}
    correct_answer: str       # "A" | "B" | "C" | "D"
    explanation: str



@dataclass
class SessionState:
    session_id: int
    questions: List[QuestionItem] = field(default_factory=list)
    messages: List[Union[HumanMessage, AIMessage]] = field(default_factory=list)




class ChatBot:
    def __init__(self, retriever, reranker_mod):
        self.retriever = retriever
        self.reranker = reranker_mod

        # Session handling
        self.sessions: List[SessionState] = []
        self.current_session: Optional[SessionState] = None
        
        # Initialize handlers
        self.question_gen = QuestionGenerator(
            retriever=retriever,
            reranker=reranker_mod
        )
        self.response_formatter = ResponseFormatter()
        self.answer_scorer = AnswerScorer()
        self.fallback = FallbackHandler()

    # Format chat history theo session (CHO LLM)
    def _format_chat_history(self, messages):
        """
        Only include messages from the current session.
        """
        if not self.current_session:
            return ""
        
        session_messages = self.current_session.messages
        formatted = []

        for msg in session_messages:
            if isinstance(msg, HumanMessage):
                formatted.append(f"User: {msg.content}")
            elif isinstance(msg, AIMessage):
                formatted.append(f"Assistant: {msg.content}")

        return "\n".join(formatted)
    


    def _parse_mcq_from_response(self, response: str) -> List[dict]:
        """
        Extract MCQ list from JSON string generated by LLM.
        Expected format:
        { "mcq": [ {...}, {...} ] }
        """
        if not response:
            return []

        try:
            data = json.loads(response)
        except JSONDecodeError:
            return []

        mcq_list = data.get("mcq", [])
        if not isinstance(mcq_list, list):
            return []

        return mcq_list

    # Start new session
    def _start_new_session(self):
        session = SessionState(
            session_id=len(self.sessions)
        )
        self.sessions.append(session)
        self.current_session = session

    
    # Save questions to current session
    def _is_valid_mcq(self, q: dict) -> bool:
        """
        Validate câu hỏi trắc nghiệm ABCD
        """
        if "question" not in q:
            return False

        options = q.get("options")
        if not isinstance(options, dict):
            return False

        required_keys = {"A", "B", "C", "D"}
        if set(options.keys()) != required_keys:
            return False

        correct = q.get("correct_answer")
        if correct not in required_keys:
            return False

        return True
    
    def _save_questions_to_session(self, original_query: str, questions: List[dict]):
        if not self.current_session:
            return

        for q in questions:
            if not self._is_valid_mcq(q):
                # Skip câu lỗi format
                continue

            item = QuestionItem(
                index=len(self.current_session.questions),
                original_query=original_query,
                generated_question=q["question"],
                options=q["options"],          # dict A-D
                correct_answer=q["correct_answer"],
                explanation=q.get("explanation", "")
            )

            self.current_session.questions.append(item)


    def ask(self, query: str, stream: bool = True):
        if not isinstance(query, str) or not query.strip():
            yield "Please provide a valid question."
            return

        query = query.strip()

        # Routing query
        label = routing_query(query)

        # LABEL 0 → GENERATE NEW MCQ QUESTIONS + SAVE TO STATE
        if label == 0:

            # luôn mở session mới
            self._start_new_session()

            try:
                # sinh MCQ JSON using handler
                response_json = self.question_gen.handle(query)
                
                # lưu hội thoại vào session
                self.current_session.messages.append(HumanMessage(content=query))
                self.current_session.messages.append(AIMessage(content=response_json))

                # parse JSON thành list QuestionItem
                mcq_items = self._parse_mcq_from_response(response_json)

                # lưu vào state
                self._save_questions_to_session(
                    original_query=query,
                    questions=mcq_items
                )
                
                # Format and stream response
                if stream:
                    yield response_json
                    return
                else:
                    return response_json
                    
            except Exception as e:
                error_msg = f"❌ Lỗi tạo câu hỏi: {str(e)[:50]}"
                if stream:
                    yield error_msg
                else:
                    return error_msg

        # LABEL 1 → CHECK ANSWER USING SAVED STATE
        if label == 1:

            # không có câu hỏi trước đó
            if (not self.current_session) or (not self.current_session.questions):
                msg = "Hiện tại chưa có câu hỏi nào để chấm đáp án."
                if stream:
                    yield msg
                    return
                else:
                    return msg

            try:
                # Use answer scorer handler
                scorer_result = self.answer_scorer.handle(
                    user_answer=query,
                    questions=self.current_session.questions
                )
                if stream:
                    yield scorer_result
                    return
                else:
                    return scorer_result
            except Exception as e:
                error_msg = f"❌ Lỗi chấm điểm: {str(e)[:50]}"
                if stream:
                    yield error_msg
                    return
                else:
                    return error_msg

        # LABEL 2 → FALLBACK NORMAL CHAT
        if label == 2:

            try:
                fallback_answer = self.fallback.handle(query)
                if stream:
                    yield fallback_answer
                    return
                else:
                    return fallback_answer
            except Exception as e:
                error_msg = f"❌ Lỗi: {str(e)[:50]}"
                if stream:
                    yield error_msg
                    return
                else:
                    return error_msg

    
    def get_current_session(self) -> Optional[SessionState]:
        return self.current_session

    def get_all_sessions(self) -> List[SessionState]:
        return self.sessions
    


